from __future__ import annotations

from . import input as _input
from .app import (
    CLARIFICATION_SKIP,
    CLARIFICATION_SKIP_TEXT,
    INPUT_CANCELLED,
    ClarificationCancelled,
    ClarificationTimeout,
    DogentCLI,
    SelectionCancelled,
    main,
)
from .editor import (
    EditorAnswer,
    EditorOutcome,
    MultilineEditRequest,
    SimpleMarkdownLexer,
    format_save_error_message,
    get_lexer_by_name,
    indent_block,
    mark_math_for_preview,
    resolve_save_path,
    wrap_markdown_code_block,
    MonokaiStyle,
)
from .input import (
    DogentCompleter,
    _clear_count_for_alt_backspace,
    _cursor_target_from_render_info,
    _darwin_clipboard_cmd,
    _read_system_clipboard,
    _should_move_within_multiline,
    _system_clipboard_supported,
    _write_system_clipboard,
    pygments_token_to_classname,
    pyperclip,
)
from .terminal import (
    TCSADRAIN,
    _TerminalSettings,
    getch,
    kbhit,
    setcbreak,
    tcsetattr,
    tcgetattr,
)

subprocess = _input.subprocess
sys = _input.sys

__all__ = [
    "CLARIFICATION_SKIP",
    "CLARIFICATION_SKIP_TEXT",
    "INPUT_CANCELLED",
    "ClarificationCancelled",
    "ClarificationTimeout",
    "DogentCLI",
    "SelectionCancelled",
    "main",
    "EditorAnswer",
    "EditorOutcome",
    "MultilineEditRequest",
    "SimpleMarkdownLexer",
    "format_save_error_message",
    "get_lexer_by_name",
    "indent_block",
    "mark_math_for_preview",
    "resolve_save_path",
    "wrap_markdown_code_block",
    "MonokaiStyle",
    "DogentCompleter",
    "_clear_count_for_alt_backspace",
    "_cursor_target_from_render_info",
    "_darwin_clipboard_cmd",
    "_read_system_clipboard",
    "_should_move_within_multiline",
    "_system_clipboard_supported",
    "_write_system_clipboard",
    "pygments_token_to_classname",
    "pyperclip",
    "TCSADRAIN",
    "_TerminalSettings",
    "getch",
    "kbhit",
    "setcbreak",
    "tcsetattr",
    "tcgetattr",
    "subprocess",
    "sys",
]
